apiVersion: v1
kind: Service
metadata:
  name: rsw-product-api
  labels:
    app: rsw-product-api
    role: api
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 8090
  selector:
    app: rsw-product-api
    role: api
    tier: backend
